### ISSUE TITLE
Error: This deferred has already been resolved

### ISSUE THREAD

**Issue by juanmanavarro** [stevetarver/excel-as-json#1] opened 2016-02-11 16:54 UTC
I'm getting this error. My code:

```js
convertExcel = require('excel-as-json').processFile;

convertExcel('prodeint_seleccion_parcelas.xlsx',
    'parcelas.json',
    false,
    function(err, data) {
        if(err) console.log(err);
    });
```
And the log:
```
throw new Error("This deferred has already been resolved");        
      ^

Error: This deferred has already been resolved
    at notifyAll (/var/www/html/test-projects/excel-json/node_modules/node-promise/promise.js:147:13)
    at Deferred.reject.reject.errback.emitError (/var/www/html/test-projects/excel-json/node_modules/node-promise/promise.js:200:5)
    at Parse.<anonymous> (/var/www/html/test-projects/excel-json/node_modules/excel/excelParser.js:29:13)
    at emitOne (events.js:83:20)
    at Parse.emit (events.js:170:7)
    at /var/www/html/test-projects/excel-json/node_modules/unzip/lib/parse.js:60:12
    at processImmediate [as _immediateCallback] (timers.js:384:17)
```

**Comment by stevetarver** [comment] 2016-02-13 03:51
@juanmanavarro, please attach prodeint_seleccion_parcelas.xlsx to simplify testing.

**Comment by juanmanavarro** [comment] 2016-02-13 17:43
@stevetarver Sorry, it contains personal information and I'm not allowed to share it. What can we do?

**Comment by stevetarver** [comment] 2016-02-28 03:26
@juanmanavarro: I have test cases that cover what I can discern from above - there is something more to this. We need to figure out a minimal reproducible test case.

If you copy the code above to a single file and run it, does the problem still happen? 
If not, your problem lies elsewhere.
If so, can you delete rows of information until the problem goes away? If so, it may be a size related problem and you could provide your header row and row count.
Perhaps you can get the size down far enough that you could remove any sensitive data.

**Comment by stevetarver** [comment] 2016-06-13 01:35
Cannot reproduce. Closing due to no issue reporter follow up and cannot reproduce this issue.

**Closed by stevetarver** 2016-06-13 01:35 UTC
